### ISSUE TITLE
Additional Icon Request

### ISSUE THREAD

**Issue by javijuji** [Jas-SinghFSU/homepage-dracula#1]
Looking great so far.  Would it be possible to add icons for the following services?

- Synology DSM
- VSCode
- Upsnap
- ChangeDetection
- Ubiquiti Unifi
- Sonarr
- Radarr
- Bazarr
- Prowlarr
- Kaizoku
- Tautulli
- Jellyfin
- Overseerr
- Kavita
- Qbitorrent
- Stirling-PDF
- MeTube
- Mealie
- BabyBuddy

![image](https://github.com/Jas-SinghFSU/homepage-dracula/assets/43682030/5416345f-d97e-4a20-a05c-4a33895b7128)

**Comment by Jas-SinghFSU** [comment]
Thank for the suggestions! Yes, I'll look into these.

**Comment by Jas-SinghFSU** [comment]
Added the requested icons. 

commit: 5392c41692f4f11db85693efb0e91725bb9e6bb6
